export { default as CatsList } from "./cats/cats-list/CatsList"
export { default as Footer } from "./footer/Footer";
export { default as HomeAbout } from "./home/home-about/HomeAbout";
export { default as HomeCats } from "./home/home-cats/HomeCats";
export { default as HomeContact } from "./home/home-contact/HomeContact";
export { default as HomeHeader } from "./home/home-header/HomeHeader";
export { default as HomeMemories } from "./home/home-memories/HomeMemories";
export { default as HomeTestimonials } from "./home/home-testimonials/HomeTestimonials";
export { default as Navbar } from "./navbar/Navbar";
